FROM ruby:{{ .RUBY_VERSION }}
MAINTAINER iron.io

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -qq -y software-properties-common wget vim

# install nginx
RUN  apt-get update && apt-get install -qq -y nginx

# install foreman
RUN gem install foreman

# downgrade bundler
RUN rm /usr/local/lib/ruby/gems/2.7.0/specifications/default/bundler-2.1.4.gemspec \
  && gem install bundler -v '1.17.3' 

# install the latest postgresql lib for pg gem
RUN apt-get install -y --force-yes libpq-dev

# install MySQL(for mysql, mysql2 gem)
RUN apt-get install -qq -y default-libmysqlclient-dev

# install dockerize
RUN wget -q https://github.com/jwilder/dockerize/releases/download/v0.2.0/dockerize-linux-amd64-v0.2.0.tar.gz \
  && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.2.0.tar.gz

RUN apt-get clean \
  && cd /var/lib/apt/lists && rm -fr *Release* *Sources* *Packages* \
  && truncate -s 0 /var/log/*log

# install Rails App
WORKDIR /app
ENV RAILS_ENV production
ONBUILD ADD Gemfile /app/Gemfile
ONBUILD ADD Gemfile.lock /app/Gemfile.lock
ONBUILD RUN bundle install --without development test
ONBUILD ADD . /app

ADD nginx-sites.conf /etc/nginx/sites-enabled/default
ADD nginx.conf /etc/nginx/nginx.conf
ADD unicorn.rb /app/config/unicorn.rb
ADD Procfile /app/Procfile

# ADD server.crt /etc/nginx/ssl/server.crt
# ADD server.key /etc/nginx/ssl/server.key

CMD foreman start -f Procfile
